AWSTemplateFormatVersion: 2010-09-09
Description: The AWS resources for the backend of the WildRydes-Site.
Metadata:
  Version: 1.0.0

Parameters:
  AccessToken:
    Description: GitHub Personal Access Token for Amplify
    Type: String

  Repository:
    Description: WildRydes site GitHub Repository
    Type: String

Resources:
  WildRydesAmplify:
    Type: AWS::Amplify::App
    Properties: 
      AccessToken: !Ref AccessToken
      Description: WildRydes Amplify App
      Name: wildrydes-site
      Platform: WEB
      Repository: !Ref Repository
